### ISSUE TITLE
Shared eslint configs

### ISSUE THREAD

**Issue by NicoZweifel** [mintlify/config#7]
### Summary

Like mentioned in https://github.com/mintlify/mint/pull/357 shared eslint configs with inheritance.

### Examples:
`@mintlify/eslint-config`
`@mintlify/eslint-config-typescript`
`@mintlify/eslint-config-react`

### inheritance:
- base -> typescript -> react -> next

**Comment by benjamin-shen** [comment]
Closed by #8
